const CONTEXT = 'LANG_EXT';

export const ErrorCodes = {
    INVALID_VO: `${CONTEXT}.INVALID_VO`,
    DUPLICATED_ELEMENT: `${CONTEXT}.DUPLICATED_ELEMENT`,
    INDEX_OUT_OF_RANGE: `${CONTEXT}.INDEX_OUT_OF_RANGE`,
} as const;
